@param io.alanda.codingkata.model.ExampleData exampleData

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Example Result</title>
</head>
<body>
<h1>Example Data Given</h1>
<p>Text: <strong>${exampleData.text()}</strong></p>
<p>Number: <strong>${exampleData.number()}</strong></p>
</body>
</html>
